# fly.toml app configuration file generated for spotify-shortcut on 2025-12-08T17:33:37-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spotify-shortcut'
primary_region = 'sjc'

[mounts]
  source = "spotify_shortcut"
  destination = "/data"

[build]
  [build.args]
    GO_VERSION = '1.24.1'

[env]
  PORT = '8080'
  SPOTIFY_TOKEN_FILE = '/data/.spotify_token.json'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
